### ISSUE TITLE
response.data.success

### ISSUE THREAD

**Issue by Alexmg86** [asabanovic/file-management-vuejs#1]
Hi!
Thanks for your lessons. One questions.  What i need return in controller, that have "response.data.success"? I'm everytime see a 'Unsuccessful Upload' :(
in console i see
{data: "", status: 200, statusText: "OK", headers: {…}, config: {…}, …}
Unsuccessful Upload

**Comment by asabanovic** [comment]
Hi Alex,

Thank you for your question. 

I left that `store` method in `HomeController` unfinished on purpose. I will actually be storing those files and returning a signal back to VueJs in my next tutorial, which should be online very soon. 

If you want to work in advance, `response.data` on VueJs side is basically the value you return from the controller method. You can easily hardcode `return 'my test';` and that will be printed in response.data on VueJs side. 

In this case, the first tutorial is basically building roads without fenders and stop lights, to the traffic might be crazy from time to time. We will sort that out. 

Now an example of what we will be doing is RESTful response, in this case I like to send whether that response was successful or not. 

```
public function store(Request $request)
    {
    	try {
                $attachments = $request->file('attachments');

    		return response()->json(array(
                'success' => true,
                'data' => $attachments,
                'errors' => []
            ), 200);

    	} catch(\Exception $e) {
    		return response()->json(array(
                'success' => false,
                'data' => 'Server error happened',
                'errors' => $e
            ), 200);
    	}
    }
```

**Comment by Alexmg86** [comment]
Adnan, thanks!
I thought yesterday and already did about the same as you wrote now. Good work :)
